# docker-compose.yml
version: '3.0'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
  web:
    tty: true
    stdin_open: true
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db